feat: add generateColorAndUpdate
Wynntils/athena-backend pull request #29
Opened 2023-06-10 20:29 UTC by DevChromium

This will generate a random color for all the guilds who do not have a color within current color bounds.

Refactored from [https://github.com/Wynntils/Artemis/pull/1554](https://github.com/Wynntils/Artemis/pull/1554)

2023-06-28 08:01 UTC, DevScyu requested changes

2023-06-28 08:01 UTC, DevScyu commented on app/Http/Libraries/Requests/Cache/TerritoryList.php
> +                $territory['guildColor'] = empty($guild->color) ? self::generateColor() : $guild->color;
This function doesn't exist?

2023-06-28 08:01 UTC, DevScyu commented on app/Http/Libraries/Requests/Cache/TerritoryList.php
> +function fromHSV($h, $s, $v, $a)
This is a dupe function of #28 we should agree to put these in a single place together

2023-08-31 12:33 UTC, kristofbolyai approved these changes

2023-08-31 12:33 UTC, merged